[default]
root = "."
libs = ['../../node_modules/', '../../']
tests = "./src/tests"
ffi = true
verbosity = 3
remappings = [
    '@sense-finance/v1-utils=./',
    '@sense-finance/v1-core=../core',
    '@sense-finance/v1-fuse=../fuse',
    'solmate/=../../node_modules/solmate/src',
    '@openzeppelin/contracts=../../node_modules/@openzeppelin/contracts'
]